ci: fix mobile teat workflow

diff --git a/.github/actions/start-android-emulator/action.yml b/.github/actions/start-android-emulator/action.yml
--- a/.github/actions/start-android-emulator/action.yml
+++ b/.github/actions/start-android-emulator/action.yml
@@ -45,5 +45,24 @@ runs:
         disable-animations: true
         script: |
           adb wait-for-device
-          pwd
+          cd packages/apps/mobile &&bun run start:dev:android &
+
+          echo "Waiting for Mobile server to start..."
+
+          timeout 60 bash -c '
+            while true; do
+              curl --silent --fail http://localhost:8081 >/dev/null 2>&1 && echo "✅ Mobile server is up!" && exit 0
+              echo -n "."
+              sleep 1
+            done
+          '
+
+          if [ $? -ne 0 ]; then
+            echo ""
+            echo "❌ Mobile server failed to start within 60 seconds"
+            exit 1
+          fi
+
+          cd packages/apps/mobile && bun run test
+
           echo "Started Android Emulator."
