ci: fix mobile teat workflow

diff --git a/.github/actions/start-mobile-on-android/action.yml b/.github/actions/start-mobile-on-android/action.yml
--- a/.github/actions/start-mobile-on-android/action.yml
+++ b/.github/actions/start-mobile-on-android/action.yml
@@ -1,63 +1,27 @@
 name: Start Mobile Server on Android
-description: Start the mobile server on Android
+description: Start the mobile server on Android and wait for it to be ready
 
 runs:
   using: composite
   steps:
-    - name: Enable KVM
+    - name: Start Mobile Server on Android
       shell: bash
       run: |
-        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
-        sudo udevadm control --reload-rules
-        sudo udevadm trigger --name-match=kvm
+        cd packages/apps/mobile
+        bun run start:dev:android &
 
-    - name: Gradle Cache
-      uses: gradle/actions/setup-gradle@v3
+        echo "Waiting for Mobile server to start..."
 
-    - name: AVD Cache
-      uses: actions/cache@v4
-      id: avd-cache
-      with:
-        path: |
-          ~/.android/avd/*
-          ~/.android/adb*
-        key: avd-33
+        timeout 60 bash -c '
+          while true; do
+            curl --silent --fail http://localhost:8081 >/dev/null 2>&1 && echo "✅ Mobile server is up!" && exit 0
+            echo -n "."
+            sleep 1
+          done
+        '
 
-    - name: Create AVD and generate snapshot for caching
-      if: steps.avd-cache.outputs.cache-hit != 'true'
-      uses: reactivecircus/android-emulator-runner@v2
-      with:
-        api-level: 33
-        arch: x86_64
-        force-avd-creation: false
-        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-        disable-animations: false
-        script: echo "Generated AVD snapshot for caching."
-
-    - name: Start Android Emulator
-      uses: reactivecircus/android-emulator-runner@v2
-      with:
-        api-level: 33
-        arch: x86_64
-        force-avd-creation: false
-        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-        disable-animations: true
-        script: |
-          cd packages/apps/mobile
-          bun run start:dev:android
-
-          echo "Waiting for Mobile server to start..."
-
-          timeout 60 bash -c '
-            while true; do
-              curl --silent --fail http://localhost:8080 >/dev/null 2>&1 && echo "✅ Mobile server is up!" && exit 0
-              echo -n "."
-              sleep 1
-            done
-          '
-
-          if [ $? -ne 0 ]; then
-            echo ""
-            echo "❌ Mobile server failed to start within 60 seconds"
-            exit 1
-          fi
+        if [ $? -ne 0 ]; then
+          echo ""
+          echo "❌ Mobile server failed to start within 60 seconds"
+          exit 1
+        fi
